### ISSUE TITLE
Can't install games, GOG shows a "Not compatible" message

### ISSUE THREAD

**Issue by micpp42** [Rall3n/galaxy-integration-amazon#1]
Installed games launch fine, but games that aren't installed have a greyed-out install button with a tooltip that says "not compatible"

**Comment by Rall3n** [comment]
That's what I don't understand.

Galaxy requires the existence of a class method to enable the installation. That method (`install_game`) does exist.

The functionality is even queried by the client itself (the `InstallGame` entry in `features`):
```jsonc
2020-06-27 09:49:00,303 - root - DEBUG - Sending data:
{
    "jsonrpc": "2.0",
    "id": "0",
    "result": {
        "platform_name": "amazon",
        "features": [
            "LaunchGame",
            "UninstallGame",
            "InstallGame",
            "ImportInstalledGames",
            "ImportOwnedGames"
        ],
        "token": TOKEN
    }
}
```

There is no documentation of any more requirements for those capabilities.

**Comment by micpp42** [comment]
Yeah I looked at the code myself just in case it was an easy fix and as far as I can tell it should be working. My one thought is maybe there's some sort of platform indicator along the lines of "GOG doesn't know that it's a windows game" or something like that. Either that or a bug in GOG I guess.

**Comment by Rall3n** [comment]
There exists a method for getting os compatability for different games. I will try it out and see if implementing this method will enable the installation of games.

**Comment by micpp42** [comment]
The update seems to have fixed it!
