### ISSUE TITLE
When asking for installing game from gog 2.0, does not work

### ISSUE THREAD

**Issue by GrgMdmn** [Rall3n/galaxy-integration-amazon#11]
When I ask for installing an amazon prime game from gog, gog launches amazon games. Then amazon games asks me for installing. I click "yes", amazon gives me "launching installer" and then nothing happens, it doesn't ask me for the installing path (I have two different installing paths)
However, manually installing from amazon games is OK, the amazon launcher gives me the choice choosing the installing path...

I think that problem may come from the choice of paths.

**Comment by Rall3n** [comment]
This is a problem to which I do not know a solution at this time.

The corresponding URI scheme for the Amazon Games app has been adopted to some extent from the Twitch app. Launching games through it works, but installing games through the URl scheme is not handled correctly. It ends up with this neutral installation prompt and not executing the installation upon confirmation.

Unfortunately I do not know of an alternative to start the installation. I´m considering to remove the `Installation` capability from the plugin for the time being.

**Comment by Rall3n** [comment]
I have released as [new version](https://github.com/Rall3n/galaxy-integration-amazon/releases/v0.4.0) (`v0.4.0`) which removed this capability completely. I will close this issue for now but will investigate further to re-introduce this function in the future.
