### ISSUE TITLE
Bomber Crew Deluxe showing has un recognized game on GOG 2.0

### ISSUE THREAD

**Issue by Scorpiopt** [Rall3n/galaxy-integration-amazon#15]
Has title says tried sync games and restarting but still shows unknown game

**Comment by Rall3n** [comment]
Similar issue as #14. API used by GOG does not recognize `Bomber Crew Deluxe` as the game `Bomber Crew: Deluxe Edition`.

Solution-testing is dependent on me finding a way to reset part of my galaxy database.

**Comment by Scorpiopt** [comment]
any update on this?

**Comment by Rall3n** [comment]
Hello @Scorpiopt,

after some thought I would recommend reporting the issue to GOG using `Report issue` in the `Cog menu`.
The game is shown as `Unknown game` which means GOGs API can't find a match, but the game is findable with the string `Bomber Crew Deluxe` on https://www.igdb.com, from where GOG gets the metadata. Also IMO the games title is unique enough to identify the correct game (there is no name conflict like in #14).

Alternatively you can rename the game to `Bomber Crew: Deluxe Edition`. I did so as well and after some time Galaxy pulled the correct information and now it shows up as an alternative to the original `Bomber Crew`.

-----

 I will still write a fix for new users, but my hands are tied for users where the Galaxy library is already populated.

**Comment by Scorpiopt** [comment]
i did report so far no changes , also happening with game Figment

**Comment by Rall3n** [comment]
I apologize for not addressing this issue for a long time. Bomber Crew seems to be no longer an "Unknown Game", as well as Figment.

I said that I will look into a fix for this, but after overthinking it again an the resolution of https://github.com/Rall3n/galaxy-integration-amazon/issues/14#issuecomment-825711806 (which also would apply here) I will not create a fix that would not have any effect at all.

I apologize again for not delivering a solution on the side of the plugin, but as said in the other issue, my hands are tied regarding this kind of issue.
