### ISSUE TITLE
Sync fails to detect new games

### ISSUE THREAD

**Issue by Scorpiopt** [Rall3n/galaxy-integration-amazon#16]
When i add games to amazon launcher , i have to remove integration and add again because no matter how many times i press sync integrations it wont detect the games

**Comment by Rall3n** [comment]
Hello @Scorpiopt,

have you started the Amazon games app between redeeming the games and checking on GOG Galaxy? (May take up to 10 minutes between launching the app and automatic synchronisation through the integration).

The games are being synchronized from a local database file managed by the Amazon games app. The integration can't synchronize new games if the database is not being kept up2date.

**Comment by Rall3n** [comment]
@Scorpiopt Are you still encountering the issue?

**Comment by Rall3n** [comment]
Will close due to inactivity.
