### ISSUE TITLE
Failed to detect game (IGDB alternate version?)

### ISSUE THREAD

**Issue by cam1170** [Rall3n/galaxy-integration-amazon#17]
When scanning, the detector failed to match "Faraway: Director's Cut", which is an alternate version of Faraway, so it shows up as "Unknown game". Maybe it's not including IGDB's alternate versions in its search? Idk how that works. The game is free with Prime now if you want to debug.
https://www.igdb.com/games/faraway-directors-cut

**Comment by Rall3n** [comment]
Hello @cam1170,

this is likely the same problem as #15. So this is not a problem with the plugin, but with the GOG Galaxy API. You would have to report this issue to GOG (using the `Report issue` form in the cog wheel dropdown on the top left).
