### ISSUE TITLE
Galaxy isn't closing the Amazon client after shutting the game down

### ISSUE THREAD

**Issue by ferrazpedro** [Rall3n/galaxy-integration-amazon#18]
Good afternoon!

I have marked the option to close the Amazon client after closing the game, but it's not working.

**Comment by Rall3n** [comment]
Hello @ferrazpedro,

this is currently not working because the plugin is currently not tracking if a game is running or not.

But this will be fixed/available in the next release.

**Comment by ferrazpedro** [comment]
Did the changes you made in the master already enabled the tracking? If you need I could help testing.

**Comment by Rall3n** [comment]
> Did the changes you made in the master already enabled the tracking? If you need I could help testing.

Oh, I did the testing, but I didn't have the time to make a new release. I'm trying to get it done tomorrow.

**Comment by Rall3n** [comment]
I have released a [new version](https://github.com/Rall3n/galaxy-integration-amazon/releases/v0.4.0) (`v0.4.0`) with the functionality to track running games and therefore automatic closing of the client.

**Comment by ferrazpedro** [comment]
Sorry for commenting in a closed issue, but I had a little question. Since you added the running status, will Galaxy start to track the time played of Amazon games too?

**Comment by Rall3n** [comment]
> Sorry for commenting in a closed issue, but I had a little question. Since you added the running status, will Galaxy start to track the time played of Amazon games too?

@ferrazpedro Game tracking is never done in Galaxy for games from other "platforms". The different library sources have to support this (and Amazon does not track time).

**Comment by ferrazpedro** [comment]
I know i'm getting WAY offtopic, but would it be possible to implement something like https://github.com/AHCoder does in their extensions to map the played time? If it's doable, may I open an issue with it? Thanks in advance and sorry for all the trouble!
