### ISSUE TITLE
No option to install games with this plugin?

### ISSUE THREAD

**Issue by DiabloStorm** [Rall3n/galaxy-integration-amazon#22]
Which means you have to open Amazon Games anyway to do this. Not very convenient.

**Comment by Rall3n** [comment]
Hello @DiabloStorm,

unfortunately this is something that can't be done with the current state of the Amazon Games App (as far as I know).

I have explained why in another issue (https://github.com/Rall3n/galaxy-integration-amazon/issues/11#issuecomment-756470719), but to summarize:
There is no known way to install a game through the usage of the provided URI scheme.

If there somehow appears to be a way, I'm happy to reintroduce this feature.
