### ISSUE TITLE
Won't connect when amazon is moved to another drive

### ISSUE THREAD

**Issue by TylerKweskin** [Rall3n/galaxy-integration-amazon#23]
As the title says. I moved the amazon gaming app from the C: drive to my E: drive and it won't see the amazon app, but did see the app when it was in the C: drive.

**Comment by Rall3n** [comment]
@RealLittlemrh 
The installation has no step to select install location afaik. How did you move the app / change install location?

**Comment by TylerKweskin** [comment]
You can literally just move the whole folder, after it's downloaded, at once to change its location and it works, though it does still add a data folder in "C:\Users\[Username]\AppData\Local\Amazon Games" but all of the games are saved in the E: drive. Hopefully, this image shows what I'm explaining correctly :D (did block out personal user in the image)
![image](https://user-images.githubusercontent.com/42455507/148033788-e76372e8-1ba3-40a6-bc9f-aa84219bc065.png)

**Comment by TylerKweskin** [comment]
Hey, I was looking through the code of "client.py" and saw it was looking for both the app.exe file and the uninstall.exe so I added them in a new folder called App in the "C:\Users[Username]\AppData\Local\Amazon Games" and placed a copy of both files and that made it work.

![image](https://user-images.githubusercontent.com/42455507/148036636-183fb253-4cf9-4616-ae44-5505aa3d50bb.png)

**Comment by Rall3n** [comment]
Hello @RealLittlemrh,

The integration checks if the Amazon Games App is installed by looking through the registry. Its registry entry has a value for the install location which is used by the integration to find the necessary files.

As you moved the app manually the path in the registry entry still pointed to the old install location.

Also this could potentially break launching Amazon games through Galaxy.

**Comment by TylerKweskin** [comment]
Well from the limited test I did it worked just fine, thanks.😃

**Comment by domnsync** [comment]
I also have the same issue. I moved the Amazon Games folder into another directory and left the Data folder on where it was originally installed at the first time. The plugin connects but can't find any game. I don't want to move the Amazon Games folder into it's original destination. What should I do to be able to see the games.
