### ISSUE TITLE
No longer fuctions.

### ISSUE THREAD

**Issue by K9Paradox** [Rall3n/galaxy-integration-amazon#25]
Error while trying to search Amazon Games App

**Comment by Rall3n** [comment]
Hello @K9Paradox,

thank you for creating this issue. Unfortunately the information you provided is not enough to properly help solving this issue.

Would you be so kind and provide more information regarding your issue?
* Do you have the Amazon Games App installed?
* Have you authenticated at least once in the app?
* Could you provide your latest plugin log file (Located at `C:\ProgramData\GOG.com\Galaxy\logs\plugin-amazon-***.log`)?

**Comment by Rall3n** [comment]
Closing this because:
1. No response from the author
2. Probably same issue as #27, caused by changes made by Amazon.
