### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by b2dmx** [Rall3n/galaxy-integration-amazon#26]
I have the Amazon Games App installed.
I have logged into the Amazon Games App.
I have the latest release of the plugin file placed as directed and advised in both Program Files & AppData.
I do not even have a log because GOG has not accepted the plugin to begin with.

**Comment by Rall3n** [comment]
Hello @b2dmx,

Would you be so kind and share the complete path to the plugins `plugin.py` file?

Could you also share the file structure inside the plugins folder?

**Comment by b2dmx** [comment]
Fresh install of both Amazon games app and GOG resolved issue.
