### ISSUE TITLE
Newly Claimed Games Don't Show As Owned

### ISSUE THREAD

**Issue by finkleroy** [Rall3n/galaxy-integration-amazon#29]
All the games I've previously claimed show as owned, but I just claimed a bunch of new games, and they don't show up, even after launching the Amazon client and leaving it open while I disconnect and reconnect the integration. This is the first time I've noticed this issue.

**Comment by Rall3n** [comment]
@finkleroy I cannot confirm the existence of this problem. Are you using the latest version of the plugin?

Would you be so kind and provide the log file for the plugin?

**Comment by Leonard03** [comment]
Not sure if it's related but I just installed this plugin for the first time and none of the games in my Amazon library are appearing. Here's my log if it helps
[plugin-amazon-c2cd2e29-8b02-35a9-86fc-3faf90255857.log](https://github.com/Rall3n/galaxy-integration-amazon/files/8961346/plugin-amazon-c2cd2e29-8b02-35a9-86fc-3faf90255857.log)

**Comment by kaniskai** [comment]
> Not sure if it's related but I just installed this plugin for the first time and none of the games in my Amazon library are appearing. Here's my log if it helps [plugin-amazon-c2cd2e29-8b02-35a9-86fc-3faf90255857.log](https://github.com/Rall3n/galaxy-integration-amazon/files/8961346/plugin-amazon-c2cd2e29-8b02-35a9-86fc-3faf90255857.log)

I just downloaded v0.5.0 and set it up. My library of Amazon games is also not registering. I don't know how to get a log though.

**Comment by Rall3n** [comment]
@Leonard03 I can't find an issue with your log file. Games are found and registered into GOG Galaxy. Even the newest ones (e.g. "Giana Sisters").

-----

@kaniskei Log files are located at `%PROGRAMDATA%\GOG.com\Galaxy\logs` and prefixed `plugin-amazon-...`. The latest log file should just have the file extension `.log`.

**Comment by kaniskai** [comment]
@Rall3n ah thank you - it didn't show up all last night but I just logged in and opened GOG today. My amazon library is now visible :D

**Comment by Leonard03** [comment]
@kaniskei Ahh, lucky.

@Rall3n Yeah, this is weird. One thing I did notice that seems kinda weird:
```
2022-06-23 19:18:58.737 [Information][ (0)] [TID 2416][galaxy_client]: Successfully imported 177 games for platform amazon with GRKs: [WholeWhackOfGames]
2022-06-23 19:18:58.738 [Information][ (0)] [TID 2416][galaxy_client]: Successfully imported 2 local games for platform 'amazon' with identifiers: 340e2d64-ef20-48dc-842d-f85ad1e06d2a(Installed), da00f127-423b-4b3c-8099-2e3480c2faad(Installed)
2022-06-23 19:18:58.741 [Information][ (0)] [TID 2416][galaxy_client]: 'amazon' local games no longer installed: 0
2022-06-23 19:18:58.741 [Information][ (0)] [TID 2416][galaxy_client]: 'amazon' new installed local games: 0
2022-06-23 19:18:58.741 [Information][ (0)] [TID 2416][galaxy_client]: 'amazon' total installed local games: 2
2022-06-23 19:18:58.848 [Information][ (0)] [TID 11468][galaxy_client]: No games on platform 'amazon' need to be marked as owned.
```

Why in the world does it think it doesn't need to make any amazon games as owned? This is right after a fresh install of the plugin.

**Comment by finkleroy** [comment]
> @finkleroy I cannot confirm the existence of this problem. Are you using the latest version of the plugin?
> 
> Would you be so kind and provide the log file for the plugin?

I'm using version 0.5.0.0. Where can I find the log file?

**Comment by Rall3n** [comment]
@finkleroy Log files are located at `%PROGRAMDATA%\GOG.com\Galaxy\logs` and prefixed `plugin-amazon-....` The latest log file should just have the file extension `.log`.

**Comment by finkleroy** [comment]
[plugin-amazon-c2cd2e29-8b02-35a9-86fc-3faf90255857.log](https://github.com/Rall3n/galaxy-integration-amazon/files/8975747/plugin-amazon-c2cd2e29-8b02-35a9-86fc-3faf90255857.log)

**Comment by Rall3n** [comment]
@Leonard03 That just says that there are no new games to be marked as owned, and that all the games listed are already marked as owned.

-----

@finkleroy I can't find any problems with your log file. As with the other, the latest claimable games show up (e.g. 'Giana Sisters'). Could you please check if you can search for the game and see if it is marked as owned?

**Comment by Leonard03** [comment]
@Rall3n Right, that's what I don't understand. I didn't find exact details in the galaxy api docs but presumably on the first connection of a newly installed plugin all of the newly connected games would need to be marked as owned - 177 in this case.

**Comment by kaniskai** [comment]
@Rall3n i didn't get time to reply yesterday but my Amazon games are not listing anymore. So strange but I've attached my log for you though based on previous messages I'm not sure how much help it is.

[plugin-amazon-c2cd2e29-8b02-35a9-86fc-3faf90255857.log](https://github.com/Rall3n/galaxy-integration-amazon/files/8979057/plugin-amazon-c2cd2e29-8b02-35a9-86fc-3faf90255857.log)

**Comment by finkleroy** [comment]
None of the latest games show as owned for me.

**Comment by montypap** [comment]
This no longer imports games. It was unable to detect new games so I reinstalled it, now it is no longer able to detect my old/installed games either.
[plugin-amazon-c2cd2e29-8b02-35a9-86fc-3faf90255857.log](https://github.com/Rall3n/galaxy-integration-amazon/files/8990983/plugin-amazon-c2cd2e29-8b02-35a9-86fc-3faf90255857.log)

**Comment by Rall3n** [comment]
After some investigation I found out that Amazon saves one of the games without its title, causing an issue within Galaxy.

A new version has been released that fixes this problem.

**Comment by finkleroy** [comment]
I disconnected and reconnected the plugin, which auto-updated it to version 0.5.1.0, but the issue persists. It's not an issue with only one game. Some of the games that were recently added to Prime Gaming show as owned, but some do not. It's possible that some, or possibly all, of the recently added games were previously given out in Prime Gaming, and that could be why they show up while the rest do not. For what it's worth, this issue is not present with the Amazon plugin for Playnite.

The recently added games that do not show as owned for me are Clouds & Sheep 2, The Darkside Detective: A Fumble in the Dark, Across the Grooves, Astrologaster, Calico, WRC 8 FIA World Rally Championship, Escape from Monkey Island, Rain World, 8Doors: Arum's Afterlife Adventure, The Metronomicon: Slay the Dance Floor, Metal Unit, Manual Samuel, The Crow's Eye, Giana Sisters: Twisted Dreams, 10 Second Ninja X, Bang Bang Racing, Gone Viral and Death Squared.

**Comment by Rall3n** [comment]
Yeah, the problem reoccurred despite the fix.

Newest version should properly fix this issue.

**Comment by Leonard03** [comment]
@Rall3n Ayyyy. We're in business here. Thanks for the fix.
Seems weird that Galaxy doesn't recover from a single missing game title though...

**Comment by finkleroy** [comment]
Everything seems fine now. I really appreciate you taking the time to get to the bottom of it and fix it.
