### ISSUE TITLE
The integration isn't showing up in the list of installed integrations

### ISSUE THREAD

**Issue by UnperfectOne** [Rall3n/galaxy-integration-amazon#3]
The integration is absent from the community integrations list within GOG Galaxy, and no games are showing up for Amazon Games.

**Comment by Rall3n** [comment]
@UnperfectOne If the integration is absent from your list, then it should have not been enabled and therefore it should have not imported any games labeled under Amazon.

Into which folder have you extracted the release archive? Complete path please.

**Comment by UnperfectOne** [comment]
I extracted the contents of the zip file into C:\Users\USERNAME\AppData\Local\GOG.com\Galaxy\plugins\installed\amazon.

**Comment by Rall3n** [comment]
@UnperfectOne Is there a file called `manifest.json` inside the extracted contents?

**Comment by UnperfectOne** [comment]
There is a `manifest.json` file.

**Comment by Rall3n** [comment]
@UnperfectOne Hm, that´s very strange. The existence of the file `manifest.json` and the path to the plugin file defined in it (and its existence) should be sufficient to make the integration appear in the list.

I would suggest you try it again with a fresh download of the latest release archive ([located here](https://github.com/Rall3n/galaxy-integration-amazon/releases/latest)).

**Comment by UnperfectOne** [comment]
It's working now! I did the exact same process as before, except this time I had the Amazon Games app open when I added the integration. Previously, I had only opened Amazon Games after copying the integration over.
