### ISSUE TITLE
Cant install games

### ISSUE THREAD

**Issue by warriorheart1112** [Rall3n/galaxy-integration-amazon#33]
![image](https://user-images.githubusercontent.com/100963372/215300699-c9768930-6f6f-4c63-b2ae-8cd4fffaa81f.png)
![image](https://user-images.githubusercontent.com/100963372/215300797-cdc234f1-424d-4ed0-ba97-d0c52d892c78.png)

**Comment by Rall3n** [comment]
@warriorheart1112 Intentional. See https://github.com/Rall3n/galaxy-integration-amazon/issues/24#issuecomment-1006061259 for the reason why.
