### ISSUE TITLE
Integration Not Updating Amazon Library

### ISSUE THREAD

**Issue by ghost** [Rall3n/galaxy-integration-amazon#36]
Added a new game to my amazon library and the plugin wouldn't import it. I uninstalled and reinstalled the plugin and it adds the game, but it would not recognize the game. The plugin imports the game as "Not Recognized" with blank data

**Comment by Rall3n** [comment]
Hello @BiggSlime ,

Missing game date is unfortunately not a problem caused by the plugin, but instead by the GOG Galaxy API. The API uses the provided title as a parameter to find the games data on the IGDB.
Only solution is to contact GOG via the in-built feedback tool.
