### ISSUE TITLE
Amazon games icon not displaying

### ISSUE THREAD

**Issue by Persian-of-Interest** [Rall3n/galaxy-integration-amazon#38]
The Amazon Games icon doesn't display, it just shows the default GOG circle like when you add a game manually

**Comment by Rall3n** [comment]
@Persian-of-Interest Are you talking about the platform icon on games and such?

These are part of and configured internally in the Galaxy 2.0 application.
Plugins don't have the ability to provide their own platform icons afaik.

So I unfortunately can't do anything about that.

**Comment by Persian-of-Interest** [comment]
> @Persian-of-Interest Are you talking about the platform icon on games and such?
> 
> These are part of and configured internally in the Galaxy 2.0 application. Plugins don't have the ability to provide their own platform icons afaik.
> 
> So I unfortunately can't do anything about that.

I'm not sure, I just noticed that an svg for the icon is included in the plugin files, but it's not actually used in GOG Galaxy. Plugins for other integrations also seem to have their icons in the plugin files itself. 

In the case of this Amazon plugin, the logo is located in the splash folder

**Comment by Rall3n** [comment]
@Persian-of-Interest That logo is displayed inside of HTML-files during setup of the plugin. As stated above, plugins can't provide icons for the Galaxy interface.
