### ISSUE TITLE
Plugin persistently uses about 1-3% CPU

### ISSUE THREAD

**Issue by micpp42** [Rall3n/galaxy-integration-amazon#5]
I've noticed that when everything is sitting idle, the python process attached to this integration seems to sit using just a couple percent of CPU, while all the others are using 0%. So I'm wondering if there's something this plugin is checking continuously where other plugins only update it intermittently?
![image](https://user-images.githubusercontent.com/16983501/90326272-c7b26800-dfc9-11ea-9d27-54a3ee9be92c.png)

**Comment by Rall3n** [comment]
Are you sure that the process belongs to this plugin? My usage is around 0 to 0.3%.

But if I had to guess, it could be the active SQLite database connection to the game database file.

**Comment by micpp42** [comment]
When I check the path it does seem to be the one belonging to the Amazon plugin
![image](https://user-images.githubusercontent.com/16983501/90345594-49a39f00-e065-11ea-80f0-12b9e5b7571b.png)
If I get a chance soon I might poke around and try to see if I can figure out why it might be happening

**Comment by Rall3n** [comment]
@micpp42 Would you mind uploading the latest log file for the plugin? Contents could provide more insights.

**Comment by micpp42** [comment]
[plugin-amazon-c2cd2e29-8b02-35a9-86fc-3faf90255857.txt](https://github.com/Rall3n/galaxy-integration-amazon/files/5083292/plugin-amazon-c2cd2e29-8b02-35a9-86fc-3faf90255857.txt)
Here's my log file

**Comment by micpp42** [comment]
Hi, so I poked around a bit with Process Monitor and it looks like what's causing the issue is the app seems to be persistently scanning through every uninstall entry in the Registry - I'm guessing this is how it detects which games are installed? I don't seem to be getting this behaviour from other plugins (which all tend to sit closer to 0% cpu) so I'm guessing what might be happening is that this process is running in full every time where other plugins basically cache it (or they're pulling it in a less resource-intensive manner)?
![image](https://user-images.githubusercontent.com/16983501/91439496-684d3580-e8b0-11ea-969b-6679668c124b.png)

**Comment by Rall3n** [comment]
Might have something to do with a little mistake I made which caused the plugin to check the local games twice per ping. But registry access in general could also be a huge performance eater.

I made some improvements which I will review and release mid next week.

**Comment by Rall3n** [comment]
@micpp42 I just released a new version of the plugin.

It replaces the registry for installed games with a query on a SQLite database.
Please confirm if this performs better than before.

**Comment by micpp42** [comment]
That looks like it's fixed it, thanks!
