### ISSUE TITLE
Missing games

### ISSUE THREAD

**Issue by mortenanakin** [Rall3n/galaxy-integration-amazon#6]
Cant make this to work.. The folder inside "plugins" directory has to be named in a special way or something? :/ I really want this to work :)

EDIT: Now i can get the plugin works, but dont detect "all" my Amazon Prime games. For example, the last they give was SEUM and Bridge Constructor, and they doesnt appear in "Amazon" list in GOG 2.0 :/

**Comment by Rall3n** [comment]
@mortenanakin Can´t confirm. Both appear in my GOG Galaxy library. Did you launch the Amazon Games App between redeeming and now? The integration fetches the games from a database which is populated by the App.

**Comment by carskaDev** [comment]
I have same issue, what is the workaround to get this to work? I get following error.
```

It seems like there was an error while trying to search for the Amazon Games App.

Please make sure the app is properly installed.
```

I've named the folder "Amazon Games App", I don't know if it makes any difference.

**Comment by Rall3n** [comment]
@carskaDev That message appears if the integration can't find the Amazon Games App. Make sure you have the app installed and launched / authorized at least once to populate the database from which this integration fetches the games.

**Comment by carskaDev** [comment]
I install the app by pasting the folder to "installed" folder right? How do I launch it after that? Sorry for being a nuisance.

//edit
Oh, I didn't know Amazon Games is an actual app you can install :D My bad. Wanted to leave this if anyone else is as stupid as me.
