### ISSUE TITLE
Logo Icon

### ISSUE THREAD

**Issue by lostpebble** [Rall3n/galaxy-integration-amazon#7]
Hi, thanks for the awesome plugin - just dropped it in and it worked perfectly.

Just one small thing I noticed is that the icon is just a circle (think its the Galaxy client's logo) when you hover over the games. Would be cool if this was represented by the Amazon "Smiley" logo. Doesn't need text, the smile will be recognizable enough.

Just a small nitpick in an otherwise great plugin.

**Comment by Rall3n** [comment]
Would be neat, but nothing I can do about. 

The icons have to be implemented by GOG Galaxy 2.0.

**Comment by lostpebble** [comment]
Ah okay, that's a bit silly that they don't allow some way of the plugin to customize that. So all community integrations just have to have that little circle until they decide its worthy of one...

**Comment by Rall3n** [comment]
The icons are not exclusive to single integrations.

They are assigned to platforms (better understood as stores/game launchers/consoles), from which the integrations define one to support. So the games added by the integration just get the platforms icon.
