### ISSUE TITLE
Keep minimized to system tray

### ISSUE THREAD

**Issue by matthewfullelove** [Rall3n/galaxy-integration-amazon#8]
Is there a way to keep the prime gaming app from launching every time I load a game?
Also, I have the setting to close the launcher automatically when I close a game on, but it doesn’t seem to be working..

Thanks in advance

**Comment by Rall3n** [comment]
@matt-26 As far as I know the app does not have a system tray mode (not even an icon).

But the second issue with the auto-closing will be investigated.

**Comment by Rall3n** [comment]
I have released a [new version](https://github.com/Rall3n/galaxy-integration-amazon/releases/v0.4.0) (`v0.4.0`) which made the functionality to close the client automatically after closing a game working.
