### ISSUE TITLE
Amazon "smile" icon missing from context menus and tooltips

### ISSUE THREAD

**Issue by telorand** [Rall3n/galaxy-integration-amazon#9]
The Amazon Smile icon is missing from tooltips and context menus, such as when mousing over a game and seeing which connected services it comes from or when selecting which service will launch a game.

Currently, it shows as the GOG Galaxy toroid icon, which can be confusing.

![GalaxyClient_wTR8g3iXQI](https://user-images.githubusercontent.com/6642272/101528084-6e918a00-3954-11eb-8338-1b98117fcd7e.png)

**Comment by Rall3n** [comment]
@telorand I would love to be able to achieve this, but my hands are tied.

The icons are defined in the application (GOG Galaxy 2.0) itself, and (as far as I know) the plugins do not have the ability to set icons.

So this is a won´t / can´t fix.

**Comment by telorand** [comment]
Oof. I thought that might be the case, but I figured I'd try to pass this along anyway. I know the review process started a long time ago, but maybe after they review the plugin, we'll finally see this change. Take care!
